### ISSUE TITLE
Bundle Demo

### ISSUE THREAD

**Issue by jmleroux** [DefaultValue/AkeneoInlineEditBundle#2]
Hey guys,
congrats for the job!
Would you have a demo of this bundle in action?
Like a short screen capture. Kazam works great on linux for this ;)

**Comment by nowiko** [comment]
@jmleroux 
Thanks!
Sure, we'll add a link to screencast to Readme for both branches.
Yep, Kazam is a great tool.

**Comment by jmleroux** [comment]
Another question, just for my knowledge: why did you not manage this extension under "FriendsOfAkeneo"?

**Comment by nowiko** [comment]
@jmleroux the matter is that AkeneoInlineEditBundle is the internal project of DefaultValue

**Comment by alexandrzhulev** [comment]
@jmleroux we have added small demos to the README for both versions
